export const gew_emotion_translations = {
  Interest: "Interese",
  Amusement: "Uzjautrinājums",
  Pride: "Lepnums",
  Joy: "Prieks",
  Pleasure: "Bauda",
  Contentment: "Apmierinātība",
  Love: "Mīlestība",
  Admiration: "Apbrīna",
  Relief: "Atvieglojums",
  Compassion: "Līdzjūtība",
  Sadness: "Skumjas",
  Guilt: "Vaina",
  Regret: "Nožēla",
  Shame: "Kauns",
  Disappointment: "Vilšanās",
  Fear: "Bailes",
  Disgust: "Riebums",
  Contempt: "Nicinājums",
  Hate: "Naids",
  Anger: "Dusmas",
  Other: "Cita",
  None: "Neviena",
};
